# Generated by Django 4.2.4 on 2023-10-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='stringnmae',
            new_name='stringname',
        ),
    ]
